spring:
        jackson:
            serialization:
                indent_output: true
                write_dates_as_timestamps: false
                write_durations_as_timestamps: false
            deserialization:
                fail_on_unknown_properties: false
            parser:
                allow_unquoted_field_names: true
        jpa:
            hibernate:
                ddl-auto: validate
            properties:
                hibernate:
                    show_sql: true
                    format_sql: true
        h2:
            console:
                enabled: true
logging:
            level:
                org:
                    flywaydb:
                        core:
                            internal:
                                dbsupport:
                                    SqlScript: debug
endpoints:
        flyway:
            web:
                enabled: true
